### ISSUE TITLE
add support for ingress annotations

### ISSUE THREAD

**Issue by wzrdtales** [smallstep/step-issuer#10]
Add support for using simply the ingress annotations like with other drivers for cert manager.

Currently an ingress annotation will try to create a certificate, but it ends up in an indefinite loop and finally memory leaks and crashes the whole cluster.

**Comment by lukasmrtvy** [comment]
Its really needed feature.

@wzrdtales, linking this https://github.com/jetstack/cert-manager/issues/3484

**Comment by larssb** [comment]
Crashes the whole cluster @wzrdtales - I guess I won't try that approach out then.

**Comment by maraino** [comment]
@wzrdtales A configuration like the following one was and is working as expected. And it also works if instead of the issuer-kind `StepIssuer` you use a `StepClusterIssuer`. In the linked cert-manager issue, you were using an invalid issuer-kind `cert-manager.io/issuer-kind: CertificateRequest`. You also need to add the secretName in the tls section.

```yaml
ingress:
  enabled: true
  annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.org/ssl-services: "step-certificates"
    cert-manager.io/issuer: step-issuer
    cert-manager.io/issuer-kind: StepIssuer
    cert-manager.io/issuer-group: certmanager.step.sm
  ingressClassName: "nginx"
  hosts:
    - host: ca.smallstep.com
      paths:
        - path: /
          type: Prefix
    - host: ca-01.smallstep.com
      paths: 
        - path: /
          type: Prefix
  tls: 
    - hosts:
      - "ca.smallstep.com"
      - "ca-01.smallstep.com"
      secretName: my-ingress-tls
```

```console
$ step certificate inspect --short https://ca.smallstep.com
X.509v3 TLS Certificate (RSA 2048) [Serial: 1612...6518]
  Subject:     ca.smallstep.com
               ca-01.smallstep.com
  Issuer:      Smallstep Intermediate CA
  Provisioner: mariano@smallstep.com [ID: nvgn...WYBQ]
  Valid from:  2022-03-17T01:49:25Z
          to:  2022-03-18T01:50:25Z
```
