### ISSUE TITLE
Can't approve cross-namespace certificates

### ISSUE THREAD

**Issue by roertel** [smallstep/step-issuer#23]
I'm struggling to get certificates to approve when the certificate is in a different namespace than the cert manager & step issuer. I set up step-certificates 1.17.1 in the "certificates" namespace with the helm chart, then set up the latest cert-manager with their helm chart and finally set up step-issuer with the latest helm chart. This is running on k3s on a learning environment on a Debian workstation. I am able to generate certificates in the "certificates" namespace, but when I do the same in the "default" namespace, I get the below error in cert-manager. 

`cert-manager/certificaterequests-approver "msg"="re-queuing item due to error processing" "error"="admission webhook \"webhook.cert-manager.io\" denied the request: status.conditions: Forbidden: user \"system:serviceaccount:certificates:cert-manager\" does not have permissions to set approved/denied conditions for issuer {step-issuer StepIssuer certmanager.step.sm}" "key"="default/test2-example-com-z5djx" `

I've attempted to create a StepClusterIssuer using YAML similar to the StepIssuer generated by helm, but the error persists. Reading through the cert-manager [code](https://github.com/cert-manager/cert-manager/blob/b1180c59ad588e73ac25b0d70a86661cf7c180e1/internal/plugin/admission/certificaterequest/approval/certificaterequest_approval.go#L19), I see the following comment, but I'm not sure how to tie it all together. 

```
// Entities will need to be able to `approve` (verb) `signers` (resource type) in
// `cert-manager.io` (group) with the name `<issuer-type>.<issuer-group>/[<certificaterequest-namespace>.]<issuer-name>`.
// For example: `issuers.cert-manager.io/my-namespace.my-issuer-name`.
// A wildcard signerName format is also supported: `issuers.cert-manager.io/*`.
```

I'm hoping that someone will be able to point me in the right direction.

**Comment by maraino** [comment]
Hi @roertel, I cannot reproduce your problem, this is my current configuration:

```
➜  helm-charts git:(master) ✗ helm ls -A
NAME             	NAMESPACE   	REVISION	UPDATED                             	STATUS  	CHART                   	APP VERSION
cert-manager     	cert-manager	1       	2022-03-16 14:51:12.241755 -0700 PDT	deployed	cert-manager-v1.7.1     	v1.7.1
step-certificates	default     	1       	2022-03-16 14:42:08.534975 -0700 PDT	deployed	step-certificates-1.18.1	0.18.1
step-issuer      	default     	1       	2022-03-16 14:43:53.071554 -0700 PDT	deployed	step-issuer-0.6.1       	0.6.0
```

I created a StepClusterIssuer that looks like:
```yaml
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-cluster-issuer
spec:
  # The CA URL.
  url: https://step-certificates.default.svc.cluster.local
  # The base64 encoded version of the CA root certificate in PEM format.
  caBundle: LS0tLS....==
  # The provisioner name, kid, and a reference to the provisioner password secret.
  provisioner:
    name: mariano@smallstep.com
    kid: 90Ll8sm5w6fGvbb7IVa63juZ-G3I7IadaTxEt2eI11Q
    passwordRef:
      namespace: default
      name: step-certificates-provisioner-password
      key: password
```

And then a certificate in a different namespace:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-smallstep-com
  namespace: test
spec:
  # The secret name to store the signed certificate
  secretName: test-smallstep-com-tls
  # Common Name
  commonName: test.smallstep.com
  # DNS SAN
  dnsNames:
    - test.smallstep.com
  emailAddresses:
    - mariano@smallstep.com
  ipAddresses:
    - 127.0.0.1
  duration: 24h
  # Renew 8 hours before the certificate expiration
  renewBefore: 8h
  # The reference to the step issuer
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-cluster-issuer
```

And the certificate is properly created:
```console
$ kubectl -n test get secrets test-smallstep-com-tls -o json | jq -r '.data["tls.crt"]' | base64 -d | step certificate inspect --short
X.509v3 TLS Certificate (RSA 2048) [Serial: 2939...5828]
  Subject:     test.smallstep.com
               127.0.0.1
               mariano@smallstep.com
  Issuer:      Smallstep Intermediate CA
  Provisioner: mariano@smallstep.com [ID: nvgn...WYBQ]
  Valid from:  2022-03-16T22:11:06Z
          to:  2022-03-17T22:12:06Z
```

@roertel I'm going to close the issue, please feel free to reopen it if it doesn't work for you.

**Comment by roertel** [comment]
> I get the same error, most likely not an bug, but how did you solved @roertel ?

IIRC, my issue was not with the configuration of step, but with the Certificate or Ingress annotations referencing `StepIssuer` and not `StepClusterIssuer` when requesting from a namespace other than where I put the issuers. Here's an ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: step-issuer
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/issuer-kind: StepClusterIssuer  # ******** I had "StepIssuer"
    ingress.kubernetes.io/force-ssl-redirect: '''true'''
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: kubernetes-dashboard
    meta.helm.sh/release-namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-dashboard
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: kubernetes-dashboard-6.0.0
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: test-dashboard.local.gd
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - test-dashboard.local.gd
    secretName: test-dashboard-local-gd
```

If you just wanted to make a certificate, it should be similar to this:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-dashboard
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: kubernetes-dashboard-6.0.0
  name: test-dashboard-local-gd
  namespace: kubernetes-dashboard
  ownerReferences:
  - apiVersion: networking.k8s.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Ingress
    name: kubernetes-dashboard
spec:
  dnsNames:
  - test-dashboard.local.gd
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer   # ******** Here is where my problem was. I had "StepIssuer"
    name: step-issuer
  secretName: test-dashboard-local-gd
  usages:
  - digital signature
  - key encipherment
```

**Comment by elixxx** [comment]
Hi, thanks for the answer. 
I deployment step-issuer via helm. 
I didn't Set following propertie to the actual namespace of cert-manager
```yaml
certManager:
  serviceAccount:
    name: cert-manager
    namespace: cert-manager

```
