### ISSUE TITLE
DNS-01 support?

### ISSUE THREAD

**Issue by gerethd** [smallstep/step-issuer#36]
Would be great if there was DNS-01 support for this, would like to replace lets encrypt with a step ca in certificate-manager but I can't find anything to show that there's support for it, and considering kid is a required field it would suggest that there isn't.

Any chance this could be a possibility?

**Comment by maraino** [comment]
Do you mean using `step-issuer` as an `ACME RA` and using it to create the TLS secrets, so you don't need to create the `StepIssuer` resources? 

How would `step-issuer` know which secrets it needs to create? The only way would be to use some logic based on the name.

Or perhaps you mean to just use step-ca's ACME implementation with `cert-manager` and replace Let's Encrypt with our CA/RA. It is possible. They don't document it, but I've done it before patching `cert-manager` like this:

```yaml
# kubectl patch deployment cert-manager -n cert-manager --patch "$(cat cm-ca-patch.yaml)"
spec:
  template:
    spec:
      containers:
      - args:
        - --v=2
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=kube-system
        name: cert-manager
        volumeMounts:
        - name: ca-pemstore
          mountPath: /etc/ssl/certs/internal-ca.pem
          subPath: internal-ca.pem
          readOnly: false
        resources: {}
      volumes:
        - name: ca-pemstore
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: ca-pemstore
```

This adds to the list of valid certs your `internal-ca.pem` that is available in a secret:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-pemstore
  namespace: cert-manager
data:
  internal-ca.pem: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
```

Then you will need the ACME Issuer pointing to step-ca's directory. Something like this:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: dns-issuer
spec:
  acme:
    email: user@example.com
    server: https://step-certificates.default.svc.cluster.local/acme/acme/directory
    privateKeySecretRef:
      name: dns-issuer-account-key
    solvers:
    - dns01: 
        cloudDNS:
          project: my-project
          serviceAccountSecretRef:
            name: prod-clouddns-svc-acct-secret
            key: service-account.json
```

Of course, you will need to use one of the supported [DNS providers](https://cert-manager.io/docs/configuration/acme/dns01/).
